- name: Create qbittorrent user
  ansible.builtin.user:
    append: yes
    group: hdd
    system: yes
    name: qbittorrent
    password_lock: yes
    create_home: false
    shell: ""
  register: qbittorrent_user

- name: Create qbittorrent downloads directory
  ansible.builtin.file:
    path: /data/qbittorrent/downloads
    state: directory
    owner: qbittorrent
    group: hdd
    mode: "700"
    recurse: yes

- name: Create qbittorrent config directory
  ansible.builtin.file:
    path: /data/qbittorrent/config
    state: directory
    owner: qbittorrent
    group: hdd
    mode: "700"
    recurse: yes

- name: Create qbittorrent hook directory
  ansible.builtin.file:
    path: /data/qbittorrent/hook
    state: directory
    owner: qbittorrent
    group: hdd
    mode: "700"
    recurse: yes

- name: Copy move downloads script
  ansible.builtin.copy:
    src: ../files/moveDownloads.sh
    dest: /data/qbittorrent/hook/moveDownloads.sh
    owner: qbittorrent
    group: hdd
    mode: "700"

- name: Download and extract qbittorrent src
  ansible.builtin.unarchive:
    remote_src: yes
    src: https://github.com/qbittorrent/qBittorrent/archive/master.zip
    dest: /data/qbittorrent/webui

- name: copy qbittorrent webui src to www
  ansible.builtin.copy:
    src: /data/qbittorrent/webui/qBittorrent-master/src/webui/www
    dest: /data/qbittorrent/webui
    remote_src: true

- name: copy qbittorrent icons src to www/public
  ansible.builtin.copy:
    src: /data/qbittorrent/webui/qBittorrent-master/src/icons
    dest: /data/qbittorrent/webui/www/public
    remote_src: true

- name: copy qbittorrent icons src to www/private
  ansible.builtin.copy:
    src: /data/qbittorrent/webui/qBittorrent-master/src/icons
    dest: /data/qbittorrent/webui/www/private
    remote_src: true

- name: Download dark qbittorrent css to public css
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/iFelix18/Dark-qBittorrent-WebUI/master/dark-qbittorrent-webui.css
    dest: /data/qbittorrent/webui/www/public/css

- name: Download dark qbittorrent css to private css
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/iFelix18/Dark-qBittorrent-WebUI/master/dark-qbittorrent-webui.css
    dest: /data/qbittorrent/webui/www/private/css

- name: inclue dark qbittorrent css in public index.html
  ansible.builtin.lineinfile:
    path: /data/qbittorrent/webui/www/public/index.html
    insertafter: "login.css"
    firstmatch: true
    line: '<link rel="stylesheet" type="text/css" href="css/dark-qbittorrent-webui.css?v=${VERSION}" \>'

- name: inclue dark qbittorrent css in private index.html
  ansible.builtin.lineinfile:
    path: /data/qbittorrent/webui/www/private/index.html
    insertafter: "Tabs.css"
    firstmatch: true
    line: '<link rel="stylesheet" type="text/css" href="css/dark-qbittorrent-webui.css?v=${VERSION}" \>'

- name: Start qbittorrent
  community.general.docker_container:
    name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent
    restart_policy: unless-stopped
    restart: yes
    memory: 512M
    cpus: 0.5
    published_ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
    volumes:
      - /data/qbittorrent/config:/config
      - /data/qbittorrent/downloads:/downloads
      - /data/qbittorrent/hook:/hook
      - /data/qbittorrent/webui:/webui
      - /mnt/hdd/Movies:/movies
      - /mnt/hdd/Tv:/tv
    env:
      TZ: "Europe/London"
      PGID: "{{ qbittorrent_user.group }}"
      PUID: "{{ qbittorrent_user.uid }}"
    container_default_behavior: compatibility

- name: allow 8080 tcp in
  community.general.ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "8080"

- name: allow 6881 tcp in
  community.general.ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "6881"

- name: allow 6881 udp in
  community.general.ufw:
    rule: allow
    direction: in
    proto: udp
    port: "6881"
