- name: Create qbittorrent user
  user:
    append: yes
    group: hdd
    system: yes  
    name: qbittorrent
    password_lock: yes
    create_home: false
    shell: ''
  register: qbittorrent_user

- name: Create qbittorrent downloads directory
  file:
    path: /data/qbittorrent/downloads
    state: directory
    owner: qbittorrent
    group: hdd
    mode: '700'
    recurse: yes

- name: Create qbittorrent config directory 
  file:
    path: /data/qbittorrent/config
    state: directory
    owner: qbittorrent
    group: hdd
    mode: '700'
    recurse: yes

- name: Create qbittorrent hook directory 
  file:
    path: /data/qbittorrent/hook
    state: directory
    owner: qbittorrent
    group: hdd
    mode: '700'
    recurse: yes

- name: Copy move downloads script
  copy:
    src: ../files/moveDownloads.sh
    dest: /data/qbittorrent/hook/moveDownloads.sh
    owner: qbittorrent
    group: hdd
    mode: '700'

- name: Download and extract qbittorrent src
  unarchive:
    remote_src: yes
    src: https://github.com/qbittorrent/qBittorrent/archive/master.zip
    dest: /data/qbittorrent/webui

- name: copy qbittorrent webui src to www
  copy:
    src: /data/qbittorrent/webui/qBittorrent-master/src/webui/www
    dest: /data/qbittorrent/webui    
    remote_src: true    

- name: copy qbittorrent icons src to www/public
  copy:
    src: /data/qbittorrent/webui/qBittorrent-master/src/icons
    dest: /data/qbittorrent/webui/www/public
    remote_src: true    

- name: copy qbittorrent icons src to www/private
  copy:
    src: /data/qbittorrent/webui/qBittorrent-master/src/icons
    dest: /data/qbittorrent/webui/www/private    
    remote_src: true    

- name: Download dark qbittorrent css to public css
  get_url:
    url: https://raw.githubusercontent.com/iFelix18/Dark-qBittorrent-WebUI/master/dark-qbittorrent-webui.css
    dest: /data/qbittorrent/webui/www/public/css

- name: Download dark qbittorrent css to private css
  get_url:
    url: https://raw.githubusercontent.com/iFelix18/Dark-qBittorrent-WebUI/master/dark-qbittorrent-webui.css
    dest: /data/qbittorrent/webui/www/private/css

- name: inclue dark qbittorrent css in public index.html
  lineinfile:
    path: /data/qbittorrent/webui/www/public/index.html
    insertafter: 'login.css'
    firstmatch: true
    line: '<link rel="stylesheet" type="text/css" href="css/dark-qbittorrent-webui.css?v=${VERSION}" \>'

- name: inclue dark qbittorrent css in private index.html
  lineinfile:
    path: /data/qbittorrent/webui/www/private/index.html
    insertafter: 'Tabs.css'
    firstmatch: true
    line: '<link rel="stylesheet" type="text/css" href="css/dark-qbittorrent-webui.css?v=${VERSION}" \>'

- name: Start qbittorrent
  docker_container:
    name: qbittorrent
    image: linuxserver/qbittorrent
    restart_policy: unless-stopped
    restart: yes
    published_ports: 
      - '6881:6881'
      - '6881:6881/udp'
      - '8080:8080'
    volumes: 
      - /data/qbittorrent/config:/config
      - /data/qbittorrent/downloads:/downloads
      - /data/qbittorrent/hook:/hook
      - /data/qbittorrent/webui:/webui
      - /mnt/hdd/Movies:/movies
      - /mnt/hdd/Tv:/tv
    env:
      TZ: 'Europe/London'
      PGID: "{{ qbittorrent_user.group }}"
      PUID: "{{ qbittorrent_user.uid }}"

- name: allow 8080 tcp in 
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '8080'      

- name: allow 6881 tcp in 
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '6881'      

- name: allow 6881 udp in 
  ufw:
    rule: allow
    direction: in
    proto: udp
    port: '6881'
