- name: Start notifier
  community.general.docker_container:
    name: notifier
    image: anshulbajpai/notifier-armv7
    restart_policy: unless-stopped
    restart: yes
    memory: 128M
    cpus: 2.0
    env:
      JAVA_OPTS: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0"  
      GOTIFY_APP_TOKEN: 'AzcXH-AMgxFL1mV'
      GOTIFY_HOST: "gotify"
      PASSPORT_RETURN_CRON: "0 0/2 17-19 * * ? *"
    container_default_behavior: compatibility
    networks:
      - name: "gotify_network"