---
- hosts: pi
  gather_facts: false
  remote_user: ansible
  become: true
  tasks:
    - name: install packages
      apt:
        name: ufw
        state: present
        update_cache: true
    - name: ufw deny default in 
      ufw:
        default: deny
        direction: incoming
    - name: allow ssh in 
      ufw:
        rule: allow
        direction: in
        proto: tcp
        port: '22'
    - name: limit ssh in 
      ufw:
        rule: limit
        direction: in
        proto: tcp
        port: '22'
    - name: enable ufw 
      ufw:
        state: enabled
