---
- hosts: pi
  gather_facts: false
  remote_user: ansible
  become: yes
  vars_prompt:
  #  - name: "nord_lynx_private_key"
      # Use following command to generate private key
      #docker run --rm --cap-add=NET_ADMIN -e TOKEN=XXX ghcr.io/bubuntux/nordvpn:get_private_key
    #  prompt: "what is your Nord VPN private key?"
  roles:
    - security
    - tmux
    - ufw
    - fail2ban
    - boot_config
    - hdd
    - reboot
    - install_docker
    - portainer
    - pihole
    - plex
    - nordlynx
    - torrent
#    - gotify
#    - notifier
