---
- hosts: pi
  gather_facts: false
  remote_user: ansible
  become: yes
#  vars_prompt:
#    - name: "nord_vpn_password"
#      prompt: "what is your Nord VPN password?"
  roles:
    - security
    - tmux
    - ufw
    - fail2ban
    - boot_config
    - hdd
    - reboot
    - install_docker
    - portainer
    - pihole
    - plex
    - nordvpn
    - torrent
#    - gotify
#    - notifier
#    - hass