---
- hosts: pi
  gather_facts: false
  remote_user: ansible
  become: yes
  roles:
     - security
     - ufw
     - fail2ban
     - boot_config
     - hdd
     - reboot
     - install_docker
     - prometheus
     - portainer
     - pihole
     - plex
     - torrent
    #  - hass
    #  - tvheadend
