---
- hosts: pi
  gather_facts: false
  remote_user: pikachu
  become: true
  vars_prompt:
  #  - name: "nord_lynx_private_key"
      # Use following command to generate private key
      #docker run --rm --cap-add=NET_ADMIN -e TOKEN=XXX ghcr.io/bubuntux/nordvpn:get_private_key
    #  prompt: "what is your Nord VPN private key?"
  #  - name: "plex_claim"
  #    prompt: "what is your Plex claim?"
  #  - name: "surfshark_wireguard_private_key"
    #  prompt: "what is your surfshark_wireguard_private_key?"
  roles:
    - security
    - ufw
    - fail2ban
    - boot_config
    - hdd
    - reboot
    - install_docker
    - portainer
    - pihole
    - plex
    - gluetun
    # - nordlynx
    - torrent
    # - gotify
    # - notifier
