---
- hosts: pi
  gather_facts: false
  remote_user: ansible
  become: yes
  roles:
     - security
     - ufw
     - fail2ban
     - bootConfig
     - hdd
     - reboot
     - installDocker
     - portainer
     - pihole
     - plex
     - torrent
     - hass
     
