- name: Update boot config
  ansible.builtin.blockinfile:
    path: /boot/firmware/config.txt
    block: |
      dtparam=audio=off
      hdmi_blanking=1
      camera_auto_detect=0
      display_auto_detect=0
      dtoverlay=disable-bt
      dtoverlay=disable-wifi
      gpu_mem_1024=16