- name: no-password-for-sudo
 #  to allow ansible to run command as sudo without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/010_pikachu-nopasswd
    line: 'pikachu ALL=(ALL) NOPASSWD: ALL'

- name: Ensure ssh root login is disabled
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Cron update openssh-server daily
  ansible.builtin.cron:
    name: "update-openssh-server"
    special_time: "daily"
    job: "sudo apt-get update && sudo apt-get upgrade -y openssh-server"

- name: ssh-users
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: AllowUsers pikachu
