- name: Ensure cgroup for docker is enabled
  ansible.builtin.lineinfile:
    backrefs: yes
    path: /boot/firmware/cmdline.txt
    regexp: '(.*?)( cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1)* rootwait'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1 rootwait'

- name: Install docker
  # FQCN not working here.
  shell: curl -fsSL https://get.docker.com | sh

- name: Install docker-ctop
  ansible.builtin.script: install-ctop.sh

- name: Add pikachu to docker group
  ansible.builtin.user:
    name: pikachu
    append: yes
    groups: docker

- name: Add ansible to docker group
  ansible.builtin.user:
    name: ansible
    append: yes
    groups: docker

- name: Create data directory
  ansible.builtin.file:
    path: /data
    state: directory
    mode: '775'

- name: Install pip3
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes
    force_apt_get: yes

- name: install python3-docker
  ansible.builtin.apt:
    name: python3-docker
    state: present
    update_cache: true
    force_apt_get: true
