- name: Ensure cgroup for docker is enabled
  ansible.builtin.lineinfile:
    backrefs: yes
    path: /boot/cmdline.txt
    regexp: '(.*?)( cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1)* rootwait'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1 rootwait'

- name: Install docker
  # FQCN not working here.
  shell: curl -sSL https://get.docker.com | sh

- name: Add pikachu to docker group
  ansible.builtin.user:
    name: pikachu
    append: yes
    groups: docker

- name: Add ansible to docker group
  ansible.builtin.user:
    name: ansible
    append: yes
    groups: docker

- name: Create data directory
  ansible.builtin.file:
    path: /data
    state: directory
    mode: '775'