
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  auth_mfa_modules:
    - type: totp

lovelace:
  mode: yaml
  dashboards:
    lovelace-default:
      mode: yaml
      filename: home-dashboard.yaml
      title: Home
      icon: mdi:desktop-mac-dashboard
      show_in_sidebar: true
      require_admin: true