- name: Create tvheadend group
  ansible.builtin.group:
    name: tvheadend

- name: Create tvheadend user
  ansible.builtin.user:
    append: yes
    group: tvheadend
    system: yes
    name: tvheadend
    password_lock: yes
    create_home: false
    shell: ''
  register: tvheadend_user

- name: Create tvheadend config directory
  ansible.builtin.file:
    path: /data/tvheadend/config
    state: directory
    owner: tvheadend
    group: tvheadend
    mode: '700'

- name: Create tvheadend recordings directory
  ansible.builtin.file:
    path: /data/tvheadend/recordings
    state: directory
    owner: tvheadend
    group: tvheadend
    mode: '700'

- name: Start tvheadend
  community.general.docker_container:
    name: tvheadend
    image: linuxserver/tvheadend:arm32v7-latest
    network_mode: host
    restart_policy: unless-stopped
    restart: yes
    volumes:
      - /data/tvheadend/config:/config
      - /data/tvheadend/recordings:/recordings
    env:
      TZ: 'Europe/London'
      PGID: "{{ tvheadend_user.group }}"
      PUID: "{{ tvheadend_user.uid }}"

- name: allow 9981 in
  community.general.ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '9981'

- name: allow 9982 in
  community.general.ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '9982'