- name: install wireguard
  ansible.builtin.apt:
    name: wireguard
    state: present
    update_cache: true
    force_apt_get: true

- name: Start NordLynx
  community.general.docker_container:
    name: nordlynx
    image: ghcr.io/bubuntux/nordlynx:20220101
    capabilities:
      - NET_ADMIN
    restart_policy: unless-stopped
    restart: yes
    memory: 128M
    cpus: 0.25
    published_ports:
      - "6881:6881" # For qbitorrent
      - "6881:6881/udp" # For qbitorrent
      - "8080:8080" # For qbitorrent
    env:
      PRIVATE_KEY: "{{ nord_lynx_private_key }}"
      NET_LOCAL: "192.168.1.0/24"
      QUERY: "filters\\[country_id\\]=209"
    container_default_behavior: compatibility

- name: allow 8080 tcp in
  community.general.ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "8080"

- name: allow 6881 tcp in
  community.general.ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "6881"

- name: allow 6881 udp in
  community.general.ufw:
    rule: allow
    direction: in
    proto: udp
    port: "6881"
