- name: Create portainer docker volume
  community.general.docker_volume:
    name: portainer_data

- name: Start portainer
  community.general.docker_container:
    name: portainer
    image: portainer/portainer-ce:2.9.0
    restart_policy: unless-stopped
    restart: yes
    memory: 32M
    cpus: 0.25
    published_ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - portainer_data:/data
    container_default_behavior: compatibility

- name: allow 9000 tcp in
  community.general.ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '9000'

