- name: Create portainer docker volume
  docker_volume:
    name: portainer_data

- name: Start portainer
  docker_container:
    name: portainer
    image: portainer/portainer
    restart_policy: unless-stopped
    restart: yes
    memory: 32M
    cpu_shares: 128
    cpuset_cpus: "3"
    published_ports: 
      - '9000:9000'
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data

- name: allow 9000 tcp in 
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '9000'      

