- name: Create homeassistant config directory
  file:
    path: /data/hass/config
    state: directory

- name: Start hass
  docker_container:
    name: hass
    image: homeassistant/raspberrypi4-homeassistant:stable
    restart_policy: unless-stopped
    restart: yes
    network_mode: host    
    volumes: 
      - /data/hass/config:/config
    env:
      TZ: 'Europe/London'

- name: allow 8123 tcp in 
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '8123'      
