- name: Create homeassistant config directory
  ansible.builtin.file:
    path: /data/hass/config
    state: directory

- name: Copy hass configuration
  ansible.builtin.copy:
    src: ../files/configuration.yaml
    dest: /data/hass/config/configuration.yaml

- name: Copy hass lovelace configuration
  ansible.builtin.copy:
    src: ../files/home-dashboard.yaml
    dest: /data/hass/config/home-dashboard.yaml

- name: Start hass
  community.general.docker_container:
    name: hass
    image: homeassistant/raspberrypi4-homeassistant:stable
    restart_policy: unless-stopped
    restart: yes
    network_mode: host    
    volumes: 
      - /data/hass/config:/config
    env:
      TZ: 'Europe/London'

- name: allow 8123 tcp in 
  community.general.ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '8123'      
