- name: Create hdd group
  ansible.builtin.group:
    name: hdd
    gid: '1111'

- name: Add pikachu to hdd group
  ansible.builtin.user:
    name: pikachu
    append: yes
    groups: hdd

- name: install exfat-fuse
  ansible.builtin.apt:
    name: exfat-fuse
    state: present
    update_cache: true
    force_apt_get: true

- name: Mount HDD on boot
  ansible.builtin.lineinfile:
    path: /etc/fstab
    backup: yes
    line: UUID=62D4-67A1 /mnt/hdd exfat defaults,auto,noatime,noexec,users,gid=1111,umask=0002,rw,nofail,x-systemd.device-timeout=30 0 0
