- name: install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true
    force_apt_get: true

- name: copy jail local
  ansible.builtin.copy:
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local
    remote_src: true

- name: Update jail local
  ansible.builtin.blockinfile:
    path: /etc/fail2ban/jail.local
    block: |
      [ssh]
      enabled  = true
      port     = ssh
      filter   = sshd
      backend  = systemd
      maxretry = 6