- name: Install docker
  shell:  curl -sSL https://get.docker.com | sh

- name: Add pikachu to docker group
  become: yes
  user:
    name: pikachu
    append: yes
    groups: docker

- name: Add ansible to docker group
  become: yes
  user:
    name: ansible
    append: yes
    groups: docker

- name: Add packages for docker compose
  become: yes
  apt:
    pkg: 
      - libffi-dev
      - libssl-dev
      - python3
      - python3-pip
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Remove packages for docker compose
  become: yes
  apt:
    name: python-configparser 
    autoclean: yes
    autoremove: yes
    state: absent
    force_apt_get: yes

- name: Install docker compose
  become: yes
  pip: 
    name: docker-compose
    executable: pip3
    