- name: Install docker
  shell:  curl -sSL https://get.docker.com | sh

- name: Add pikachu to docker group
  user:
    name: pikachu
    append: yes
    groups: docker

- name: Add ansible to docker group
  user:
    name: ansible
    append: yes
    groups: docker