global:
  scrape_interval:     1m
  evaluation_interval: 1m

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: docker_daemon
    static_configs:
      - targets: ['localhost:9323']
  - job_name: cadvisor
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:8090']