- name: Start traefik
  docker_container:
    name: traefik
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker=true --providers.docker.exposedbydefault=false --entrypoints.web.address=:80
    published_ports: 
      - '8080:8080'
      - '80:80'
    restart_policy: unless-stopped
    restart: yes
    network_mode: proxy
    networks:
      - name: proxy
    networks_cli_compatible: yes      
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock

- name: allow 8080 in 
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '8080'      
    
- name: allow 80 in 
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '80'      