- name: Create a network for traefik
  docker_network:
    name: proxy

- name: Start traefik
  docker_container:
    name: traefik
    domainname: local
    image: traefik:v2.2
    command: 
      - --providers.docker=true
      - --providers.docker.network=proxy
      - --providers.docker.exposedbydefault=false
      - --api.insecure=true
      - --entrypoints.http.address=:80
    published_ports: 
      - '8080:8080'
      - '80:80'
    restart_policy: unless-stopped
    restart: yes
    network_mode: proxy
    networks:
      - name: proxy
    networks_cli_compatible: yes      
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    dns_servers:
      - '192.168.1.164'
      - '1.1.1.1'

- name: allow 8080 in 
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '8080'      
    
- name: allow 80 in 
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '80'      
