- name: Create plex user
  ansible.builtin.user:
    group: hdd
    system: yes
    name: plex
    password_lock: yes
    create_home: false
    shell: ''
  register: plex_user

- name: Create plex config directory
  ansible.builtin.file:
    path: /data/plex/config
    state: directory
    owner: plex
    group: hdd
    mode: '770'

- name: Start plex
  community.general.docker_container:
    name: plex
    image: linuxserver/plex:1.41.6
    restart_policy: unless-stopped
    restart: yes
    memory: 1024M
    network_mode: host
    volumes:
      - /data/plex/config:/config
      - /mnt/hdd/Movies:/movies
      - /mnt/hdd/Tv:/tv
      - /mnt/hdd/Pictures:/pictures
    env:
      # PLEX_CLAIM: "{{ plex_claim }}"
      TZ: 'Europe/London'
      PGID: "{{ plex_user.group }}"
      PUID: "{{ plex_user.uid }}"
      VERSION: docker
    container_default_behavior: compatibility

- name: allow 32400 in
  community.general.ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '32400'
