- name: Create pihole etc directory
  ansible.builtin.file:
    path: /data/pihole/etc-pihole
    state: directory

- name: Create pihole dnsmasqd directory
  ansible.builtin.file:
    path: /data/pihole/etc-dnsmasqd
    state: directory

- name: Start pihole
  community.general.docker_container:
    name: pihole
    hostname: pihole
    image: pihole/pihole:2025.08.0
    memory: 512M
    cpus: 1
    published_ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '80:80/tcp'
      - '443:443/tcp'
    restart_policy: unless-stopped
    restart: yes
    volumes:
      - /data/pihole/etc-pihole/:/etc/pihole/
      - /data/pihole/etc-dnsmasqd/:/etc/dnsmasq.d/
    dns_servers:
      - '127.0.0.1'
    env:
      TZ: 'Europe/London'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_misc_etc_dnsmasq_d: 'true'
      FTLCONF_dns_upstreams: '1.1.1.1;1.0.0.1'  
      FTLCONF_dns_dnssec: 'true'
      FTLCONF_dns_bogusPriv: 'true'
      FTLCONF_dns_domainNeeded: 'true'
      FTLCONF_dns_revServers: 'true,192.168.1.0/24,192.168.1.1,local'
    container_default_behavior: compatibility

- name: allow 53 tcp in
  community.general.ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '53'

- name: allow 53 udp in
  community.general.ufw:
    rule: allow
    direction: in
    proto: udp
    port: '53'

- name: allow 80 tcp in
  community.general.ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '80'

- name: allow 443 tcp in
  community.general.ufw:
    rule: allow
    direction: in
    proto: tcp
    port: '443'